mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^polls/', include('polls.urls')),
	url(r'^admin/', admin.site.urls),
	url(r'^accounts/', include('registration.backends.default.urls')),
]

polls/urls.py
from django.conf.urls import url, patterns, include

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'polls'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^predict/$', views.predict, name='predict'),
	url(r'^promotions/$', views.promotions, name='promotions'),
	url(r'^holt/$', views.inputs, name='holt'),
	url(r'^linechart/$', views.demo_linechart, name='demo_linechart'),

	#url(r'^predict/$', views.PredictView.as_view(), name='predict'),
	url(r'^list/$', views.list, name='list'),
	url(r'^accounts/', include('registration.backends.default.urls')),
]

#urlpatterns = patterns('',
#    (r'^', include('polls.urls')),
#		) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# The long code...
	
	# ex: /polls/
#	url(r'^$', views.index, name='index'),
	#ex: /polls/5/
#	url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
	# ex: /polls/5/results/
#	url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
	# ex: /polls/5/vote/
#	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	# added the word 'specifics'
	#url(r'^specifics/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
#	]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	
	def __str__(self):
		return self.question_text
		
	def was_published_recently(self):
#		now = timezone.now()
#		return now - datetime.timedelta(days=1) <= self.pub_date <= now
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'
	
class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text
		
class Document(models.Model):
    #docfile = models.FileField(upload_to='documents/%Y/%m/%d')
	docfile = models.FileField(upload_to='documents')
	def __str__(self):
		return self.document_text
		
	def was_published_recently(self):
#		now = timezone.now()
#		return now - datetime.timedelta(days=1) <= self.pub_date <= now
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

polls/forms.py
# -*- coding: utf-8 -*-
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

polls/views.py
from __future__ import division # for the def holt(request)

from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from pandas import * # for Triple Exponential
import pandas as pd
import numpy as np
import math
import re
from sklearn.ensemble import RandomForestRegressor

from .models import Document
from .forms import DocumentForm

from .models import Choice, Question

from sys import exit # for the def holt(request)
from math import sqrt # for the def holt(request)
from numpy import array # for the def holt(request)
from scipy.optimize import fmin_l_bfgs_b # for the def holt(request)
import matplotlib.pyplot as plt # for the def holt(request)

import random # for def demo_linechart
import datetime # for def demo_linechart
import time # for def demo_linechart

import plotly.tools as tls # for def demo_linechart v2
tls.set_credentials_file(username='gaspardorey',api_key='fobabamwnw') # for def demo_linechart v2

from sqlalchemy import create_engine # database connection  # # for def demo_linechart
import datetime as dt # for def demo_linechart
import sqlite3 # to delete database # # for def demo_linechart

import plotly.plotly as py # interactive graphing # # for def demo_linechart
from plotly.graph_objs import Bar, Scatter, Marker, Layout # for def demo_linechart
import plotly.graph_objs as go # for def demo_linechart

class IndexView(generic.ListView):
	template_name = 'polls/base.html' #index.html'
	context_object_name = 'latest_question_list'
	
	def get_queryset(self):
		"""Return the last five published questions (not including those set to be
		published in the future
		"""
		return Question.objects.filter(
			pub_date__lte=timezone.now()
		).order_by('-pub_date')[:5]
		#return Question.objects.order_by('-pub_date')[:5]
		
		
class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
		"""
		Excludes any questions that aren't published yet.
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())

	
class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'
	

def vote(request, question_id):
#	return HttpResponse("You're voting on question %s." % question_id)
		question = get_object_or_404(Question, pk=question_id)
		try:
			selected_choice = question.choice_set.get(pk=request.POST['choice'])
		except (KeyError, Choice.DoesNotExist):
			# Redisplay the question voting form.
			return render(request, 'polls/detail.html', {
				'question': question,
				'error_message': "You didn't select a choice.",
			})
		else:
			selected_choice.votes += 1
			selected_choice.save()
			# Always return an HttpResponseRedirect after successfully dealing
			# with POST data. This prevents data from being posted twice if a 
			# user hits the Back button.
			return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))




# Create your views here.

#def index(request):
#	return HttpResponse("Hello, world. You're at the polls index.")

#def index(request):
#	latest_question_list = Question.objects.order_by('-pub_date')[:5]
#	# We could leave this in but we would be hard coding items
#	# It is better to take the design out:
#	# output = ', '.join([q.question_text for q in latest_question_list])
#	template = loader.get_template('polls/index.html')
#	context = {
#		'latest_question_list': latest_question_list,
#		}
#	return HttpResponse(template.render(context, request))

#def index(request):
#	latest_question_list = Question.objects.order_by('-pub_date')[:5]
#	context = {'latest_question_list': latest_question_list}
#	return render(request, 'polls/index.html', context)
	
	
#def detail(request, question_id):
#	return HttpResponse("You're looking at question %s." % question_id)
#	try:
#		question = Question.objects.get(pk=question_id)
#	except Question.DoesNotExist:
#		raise Http404("Question does not exist")
#	question = get_object_or_404(Question, pk=question_id)
#	return render(request, 'polls/detail.html', {'question': question})
	
#def results(request, question_id):
#	question = get_object_or_404(Question, pk=question_id)
#	return render(request, 'polls/results.html', {'question':question})

   
		
def predict(request):
	dsProgReports = pd.read_csv('C:/Users/gadorey/projects/myPandas/School_Progress_Reports_-_All_Schools_-_2009-10.csv')
	dsDistrict = pd.read_csv('C:/Users/gadorey/projects/myPandas/School_District_Breakdowns.csv')
	dsClassSize = pd.read_csv('C:/Users/gadorey/projects/myPandas/2009-10_Class_Size_-_School-level_Detail.csv')
	dsAttendEnroll = pd.read_csv('C:/Users/gadorey/projects/myPandas/School_Attendance_and_Enrollment_Statistics_by_District__2010-11_.csv')[:-2] # last two rows are bad
	dsSATs = pd.read_csv('C:/Users/gadorey/projects/myPandas/SAT__College_Board__2010_School_Level_Results.csv') # Dependent

	# >>> pdPredict.dsSATs.info()


	# ESTRATÉGIA:
	#Target Variable and Joining Strategy
	# We are going to build a dataset to predict Critical Reading Mean, Mathematics Mean, and
	# Writing Mean for each school (identified by DBN).
	# After digging around in Excel (or just taking my word for it) we identify the following join
	# strategy (using SQL-esque pseudocode):

	# dsSATS join dsClassSize on dsSATs['DBN'] = dsClassSize['SCHOOL CODE']
	# join dsProgReports on dsSATs['DBN'] = dsProgReports['DBN']
	# join dsDistrct on dsProgReports['DISTRICT'] = dsDistrict['JURISDICTION NAME']
	# join dsAttendEnroll on dsProgReports['DISTRICT'] = dsAttendEnroll['District']


	PrimNormalized = pd.DataFrame(data=[dsProgReports['DBN'][:5], dsSATs['DBN'][:5], dsClassSize['SCHOOL CODE'][:5]])

	# Strip the first two characters off the DBNs so we can join to School Code
	dsProgReports.DBN = dsProgReports.DBN.map(lambda x: x[2:])
	dsSATs.DBN=dsSATs.DBN.map(lambda x: x[2:])


	#We can now see the keys match:
	# use slicing instead of "take" ie [:5] instead of "take(range(5))"
	data=pd.DataFrame(data=[dsProgReports['DBN'][:5], dsSATs['DBN'][:5], dsClassSize['SCHOOL CODE'][:5]])
	#print('Data Joined: ')
	#print(data)
	#print('******')


	# Show the key mismatchs [13]
	# For variety's sake, using slicing ([:3]) sintax instead of .take()
	data= pd.DataFrame(data=[dsProgReports['DISTRICT'][:3], dsDistrict['JURISDICTION NAME'][:3], dsAttendEnroll['District'][:3]])
	#print('Keys Mismatch')
	#print(data)
	#print('******')

	# Extract well-formed district key values [14]
	# Note the astype(int) at the end of these lines to coerce the column to a 
	# numeric type:

	dsDistrict['JURISDICTION NAME']=dsDistrict['JURISDICTION NAME'].map(lambda x: re.match(r'([A-Za-z]*\s)([0-9]*)',x).group(2)).astype(int)
	dsAttendEnroll.District = dsAttendEnroll.District.map(lambda x: x[-2:]).astype(int)

	# We can now see the keys match
	new_data=pd.DataFrame(data=[dsProgReports['DISTRICT'][:3],dsDistrict['JURISDICTION NAME'][:3],dsAttendEnroll['District'][:3]])

	#print('Keys Match = ')
	#print(new_data)
	#print('******')

	# Reindexing
	dsProgReports = dsProgReports.set_index('DBN')
	dsDistrict = dsDistrict.set_index('JURISDICTION NAME')
	dsClassSize = dsClassSize.set_index('SCHOOL CODE')
	dsAttendEnroll = dsAttendEnroll.set_index('District')
	dsSATs = dsSATs.set_index('DBN')

	#print('dsProgReports = ')
	#print(dsProgReports)
	#print('******')
	#print('dsSATs = ')
	#print(dsSATs)
	#print('******')

	# We can see the bad values
	# dsSATs['Critical Reading Mean'].take(range(5))
	new_dsSATs = dsSATs['Critical Reading Mean'][:5]
	#print('Here is an example of the "s" values in dsSATs = ')
	#print(new_dsSATs)
	#print('******')

	# Now we filter it out
	# We create a boolean vector mask. Open question as to whether this is 
	# semantically ideal....
	mask = dsSATs['Number of Test Takers'].map(lambda x: x != 's')
	dsSATs = dsSATs[mask]

	# Cast fields to integers. Ideally we should not need to be this explicit.
	dsSATs['Number of Test Takers'] = dsSATs['Number of Test Takers'].astype(int)
	dsSATs['Critical Reading Mean'] = dsSATs['Critical Reading Mean'].astype(int)
	dsSATs['Mathematics Mean'] = dsSATs['Mathematics Mean'].astype(int)
	dsSATs['Writing Mean'] = dsSATs['Writing Mean'].astype(int)

	#print('Mask = ')
	#print(mask)
	#print('*********')
	#print('Old dsSATs = ')
	#print(new_dsSATs)
	#print('*********')
	#print('New dsSATs = ')
	#print(dsSATs['Critical Reading Mean'][:5])
	#print('*********')
	#print('New dsSATs complete = ')
	#print(dsSATs[:5])
	#print('*********')


	# The shape of the data:
	#print('dsClassSize.columns = ',dsClassSize.columns)
	#print('*************')
	#print('dsClassSize.take([0,1,10]).values = ',dsClassSize.take([0,1,10]).values)
	#print('*************')

	# Extracting the Pupil-Teacher ratio:

	# 	1) a) Take the Column
	dsPupilTeacher = dsClassSize.filter(['SCHOOLWIDE PUPIL-TEACHER RATIO'])
	#print('Old dsPupilTeacher = ')
	#print(dsPupilTeacher[:15])
	#print('*************')

	# 		b) And filter out blank rows
	mask = dsPupilTeacher['SCHOOLWIDE PUPIL-TEACHER RATIO'].map(lambda x: x > 0)
	dsPupilTeacher = dsPupilTeacher[mask]
	#print('mask = ')
	#print(mask[:15])
	#print('*************')
	#print('New dsPupilTeacher = ')
	#print(dsPupilTeacher[:15])
	#print('*************')

	# 		c) Then drop the original dataset
	dsClassSize = dsClassSize.drop('SCHOOLWIDE PUPIL-TEACHER RATIO', axis=1)
	#print('New dsClassSize = ')
	#print(dsClassSize[:15])
	#print('*************')

	#	2) Drop non-numeric fields
	dsClassSize=dsClassSize.drop(['BORO','CSD','SCHOOL NAME','GRADE ','PROGRAM TYPE','CORE SUBJECT (MS CORE and 9-12 ONLY)','CORE COURSE (MS CORE and 9-12 ONLY)','SERVICE CATEGORY(K-9* ONLY)','DATA SOURCE'], axis=1)
	#print('New non-numeric dsClassSize = ')
	#print(dsClassSize[:15])
	#print('*************')

	#	3) Build features from dsClassSize

polls/templates/polls/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Static Top Navbar Example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/bootstrap.min.css' %}" />
	<!-- <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> -->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'polls/css/navbar-static-top.css' %}" />

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- <script src="../../assets/js/ie-emulation-modes-warning.js"></script> -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	
	
  </head>

  <body>
	
	{% include 'polls/navbar.html' %} <!-- This loads a template file, in this case, polls/navbar.html -->
	
	
    <div class="container">
	
	<!-- blocks: allow us to replace things based on inheritance. -->
	
	{% block content %}
	
		
	{% endblock %}


    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

<!--
<ul>
{% for choice in question.choice_set.all %}
	<li>{{ coice.choice_text }}</li>
{% endfor %}
</ul>
-->

polls/templates/polls/holt.html
{% extends 'polls/base.html' %}
	
{% block content %}

<h1>Sales Prediction</h1>

<iframe width="100%" height="500" frameborder="0" scrolling="no" src="https://plot.ly/~gaspardorey/1.embed"></iframe>




	
{% endblock %}

polls/templates/polls/home.html
{% extends "base.html" %}
<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
	<h1>Navbar example</h1>
	<p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
	<p>To see the difference between static and fixed top navbars, just scroll.</p>
	<p>
		<a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
	</p>
</div>
	  
{% block content %}
<h1>{{ title }}</h1>

{{ user }}

{{ request.user }}

<form method='POST' action=''>{% csrf_token %}
{{ form.as_p }}

<input type='submit' value='Sign Up' />

</form>

{% endblock %}

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>This is my heading</h1>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/linechart.html
<!doctype html>
{% extends 'polls/base.html' %}
	
{% block content %}

<html>

<head>
	<title>D3 Tutorial</title>
    <script src="http://d3js.org/d3.v3.min.js"></script>

</head>

<body>
	<iframe width="500" height="500" frameborder="0" scrolling="no" src="https://plot.ly/~gaspardorey/8.embed"></iframe>

    <script>

	</script>



</body>

</html>

	
{% endblock %}

polls/templates/polls/linechart_old.html
<!-- {% extends 'polls/base.html' %} -->
<!-- {% block content %} -->
<!-- {% load nvd3_tags %} -->
<!-- <p>NVD3_tags loaded or not?</p> -->

<!doctype html>

<html>

<head>
    <!-- {# Jquery CDN : Needed when using jquery_on_ready=True #} -->
    <script src="http://d3js.org/d3.v3.min.js"></script>
	<!-- {% include_chart_jscss %}
    {% load_chart charttype chartdata chartcontainer extra %}
	<p>Linechart or not?</p> -->

</head>
<body>
    <script>
	
		<!-- d3.csv("C:\Users\gadorey\projects\myPandas\holt_sales.csv", function(data){ -->
		d3.json("C:\Users\gadorey\projects\myPandas\holt_sales.json", function(data){ 
		
			var canvas = d3.select("body").append("svg")
				.attr("width", 500)
				.attr("height", 500)
				
			canvas.selectAll("rect")
				.data(data)
				.enter()
					.append("rect")
					.attr("width", function(d) { return d.Sales * 10; })
					.attr("height", 50)
					.attr("y", function(d,i) {return i * 50; })
					.attr("fill", "blue")
				
		})
		
	</script>


	<!-- {% include_container chartcontainer %}
	{{ linechart }}
	<p>chartcontainer included or not?</p> -->

</body>

{% endblock %}

polls/templates/polls/linechart_old2.html
<!doctype html>

<html>

<head>
	<title>D3 Tutorial</title>
    <script src="http://d3js.org/d3.v3.min.js"></script>

</head>

<body>
    <script>
	
		d3.json("holt_sales.json", function(data) { 
		
			var canvas = d3.select("body").append("svg")
				.attr("width", 500)
				.attr("height", 500)
				
			canvas.selectAll("rect")
				.data(data)
				.enter()
					.append("rect")
					.attr("width", function(d) { return d.Sales * 10; })
					.attr("height", 50)
					.attr("y", function(d,i) {return i * 500; })
					.attr("fill", "blue")
				
		})
		
	</script>



</body>

polls/templates/polls/linechart_works.html
<!doctype html>
{% extends 'polls/base.html' %}
	
{% block content %}

<html>

<head>
	<title>D3 Tutorial</title>
    <script src="http://d3js.org/d3.v3.min.js"></script>

</head>

<body>
    <script>
	
			var dataArray = [20,40,50];
		
			var canvas = d3.select("body")
				.append("svg")
				.attr("width", 500)
				.attr("height", 500);
				
			var bars = canvas.selectAll("rect")
				.data(dataArray)
				.enter()
					.append("rect")
					.attr("width", function(d) { return d * 10; })
					.attr("height", 50)
					.attr("y", function(d,i) {return i * 100; })
					.attr("fill", "blue");
					
			
			
	</script>



</body>

</html>

	
{% endblock %}

polls/templates/polls/linechart_works_D3_work on this one.html
<!doctype html>
{% extends 'polls/base.html' %}
	
{% block content %}

<html>

<head>
	<title>D3 Tutorial</title>
    <script src="http://d3js.org/d3.v3.min.js"></script>

</head>

<body>
	
    <script>

			d3.csv("holt_sales.csv", function(datasetText) {

			var parsedCSV = d3.csv.parseRows(datasetText);

			var sampleHTML = d3.select("#viz")
				.append("table")
				.style("border-collapse", "collapse")
				.style("border", "2px black solid")

				.selectAll("tr")
				.data(parsedCSV)
				.enter().append("tr")

				.selectAll("td")
				.data(function(d){return d;})
				.enter().append("td")
				.style("border", "1px black solid")
				.style("padding", "5px")
				.on("mouseover", function(){d3.select(this).style("background-color", "aliceblue")})
				.on("mouseout", function(){d3.select(this).style("background-color", "white")})
				.text(function(d){return d;})
				.style("font-size", "12px");
			});
			
	</script>



</body>

</html>

	
{% endblock %}

polls/templates/polls/list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>File Upload</title>   
    </head>
    <body>
    <!-- List of uploaded documents -->
    {% if documents %}
        <ul>
        {% for document in documents %}
            <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No documents.</p>
    {% endif %}

        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'polls:list' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>
            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>
            <p><input type="submit" value="Upload" /></p>
        </form>
    </body>
</html> 

polls/templates/polls/navbar.html
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Triangle</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
			<li><a href="#contact">Contact</a></li>
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
		  <form class='navbar-form navbar-right' method='POST' action=''>{% csrf_token %}
			<div class='form-group'>
				<input type='text' class='form-control' name='username' placeholder='Username' />
			</div>
			<div class='form-group'>
				<input type='text' class='form-control' name='password' placeholder='Password' />
			</div>
			<button type='submit' class='btn btn-default'>Login</button>
		  </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>
            <li><a href="../navbar-fixed-top/">Fixed top</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

polls/templates/polls/predict.html
{% extends 'polls/base.html' %}
	
{% block content %}

<h1>Predictions</h1>

{{ rmse }}<p>
{{ nrmse }}</p>


	
{% endblock %}

polls/templates/polls/results.html
 <h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>